[versions]
notchity = "8bf2b5125e"
shadow = "8.3.0"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
notchity = { group = "com.github.kvdpxne", name = "notchity", version.ref = "notchity" }